name: Build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  id-token: write
  pages: write

env:
  RUSTFLAGS: --cfg=web_sys_unstable_apis

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.1
        with:
          version: latest

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: trunk build --release

      - name: Setup GitHub Pages
        if: github.event_name == 'push'
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
            path: dist

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v4
